name: tgp
channels:
  - pytorch
  - nvidia                    # remove for cpu installation
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pytorch>=1.8
  - pytorch-cuda==12.1         # remove for cpu installation
  - pyg>=2.0
  - pytorch-cluster
  - pytorch-scatter
  - pytorch-sparse
  - numpy<2
  - scikit-learn
  - pip
  - pip:
      - fsspec==2024.3.1
      - pygsp