name: CI
on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with: { python-version: "3.10" }
      - name: Install project & dev tools
        run: |
          pip install -r pre-requirements.txt
          pip install -e .[dev]
      - name: Check linting
        run: ruff check .
      - name: Check code formatting
        run: ruff format --check .
      - name: Run tests with coverage
        run: pytest
